---
kind: pipeline
name: go1.12

steps:

- name: test
  pull: default
  image: golang:1.12
  environment:
    GO111MODULE: on
    GOPROXY: https://goproxy.cn
  commands:
    - go build -v
    - go vet ./...
    - go test -v -race -coverprofile=coverage.txt -covermode=atomic
  when:
    event:
    - push
    - pull_request